# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: server

stages:
- stage: Release
  displayName: "Pixel Release"
  jobs:
  - job: Library_scan
  - job: Custom_scan
    dependsOn: Library_scan
  - job: Selenium_test
    dependsOn: Custom_scan
  - job: Deploy
    dependsOn: Selenium_test
    steps:
      - task: ServiceNow-DevOps-Server-Change-Acceleration@1
        inputs:
          connectedServiceName: 'DevOps Connection'

